/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserAgreementRouteImport } from './routes/user-agreement'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileProfileIdRouteImport } from './routes/profile.$profileId'
import { Route as PreviewProjectIdRouteImport } from './routes/preview.$projectId'

const UserAgreementRoute = UserAgreementRouteImport.update({
  id: '/user-agreement',
  path: '/user-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdRoute = ProfileProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => ProfileRoute,
} as any)
const PreviewProjectIdRoute = PreviewProjectIdRouteImport.update({
  id: '/preview/$projectId',
  path: '/preview/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/creators': typeof CreatorsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/user-agreement': typeof UserAgreementRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/creators': typeof CreatorsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/user-agreement': typeof UserAgreementRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/creators': typeof CreatorsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/user-agreement': typeof UserAgreementRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/awards'
    | '/creators'
    | '/privacy-policy'
    | '/profile'
    | '/user-agreement'
    | '/preview/$projectId'
    | '/profile/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/awards'
    | '/creators'
    | '/privacy-policy'
    | '/profile'
    | '/user-agreement'
    | '/preview/$projectId'
    | '/profile/$profileId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/awards'
    | '/creators'
    | '/privacy-policy'
    | '/profile'
    | '/user-agreement'
    | '/preview/$projectId'
    | '/profile/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AwardsRoute: typeof AwardsRoute
  CreatorsRoute: typeof CreatorsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  UserAgreementRoute: typeof UserAgreementRoute
  PreviewProjectIdRoute: typeof PreviewProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-agreement': {
      id: '/user-agreement'
      path: '/user-agreement'
      fullPath: '/user-agreement'
      preLoaderRoute: typeof UserAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId': {
      id: '/profile/$profileId'
      path: '/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof ProfileProfileIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/preview/$projectId': {
      id: '/preview/$projectId'
      path: '/preview/$projectId'
      fullPath: '/preview/$projectId'
      preLoaderRoute: typeof PreviewProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileProfileIdRoute: typeof ProfileProfileIdRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileProfileIdRoute: ProfileProfileIdRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AwardsRoute: AwardsRoute,
  CreatorsRoute: CreatorsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  UserAgreementRoute: UserAgreementRoute,
  PreviewProjectIdRoute: PreviewProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
